baseURL = "https://gist.ymotongpoo.dev"
languageCode = "ja"
title = "gist::ymotongpoo"
theme = "archie"
hasCJKLanguage = true
copyright = "&copy;Yoshi Yamaguchi"
googleAnalytics = "UA-6420772-10"

pygmentsstyle = "nord"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 20
summaryLength = 10

[params]
mode = "auto"
subtitle = "A brain dumps by Yoshi Yamaguchi."
mainSections = ["posts"]
mathjax = true
katex = true
featherIconsCDN = true
amazonJpAffiliate = "ymotongpoo-22"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ymotongpoo"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ymotongpoo"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[taxonomies]
tags = "tags"
