baseURL = "http://gist.ymotongpoo.dev"
languageCode = "ja"
title = "gist::ymotongpoo"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "&copy;Yoshi Yamaguchi 2021-"
googleAnalytics = "UA-6420772-10"

[params]
description = "A brain dumps by Yoshi Yamaguchi."
twitter = "ymotongpoo"
useIcon = true
useTwitterCard = true
shareTo = ["Twitter", "Hatena", "Facebook"]
showFooterCredits = true